# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'KS34460A.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QLabel, QPushButton, QSizePolicy, QSpinBox,
    QTextEdit, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(768, 434)
        self.commandLabel = QLabel(Widget)
        self.commandLabel.setObjectName(u"commandLabel")
        self.commandLabel.setGeometry(QRect(10, 70, 131, 16))
        self.readButton = QPushButton(Widget)
        self.readButton.setObjectName(u"readButton")
        self.readButton.setGeometry(QRect(170, 140, 75, 23))
        self.cbButton = QPushButton(Widget)
        self.cbButton.setObjectName(u"cbButton")
        self.cbButton.setGeometry(QRect(670, 140, 81, 23))
        self.readTextEdit = QTextEdit(Widget)
        self.readTextEdit.setObjectName(u"readTextEdit")
        self.readTextEdit.setGeometry(QRect(10, 200, 741, 181))
        self.titleLabel = QLabel(Widget)
        self.titleLabel.setObjectName(u"titleLabel")
        self.titleLabel.setGeometry(QRect(10, 11, 91, 20))
        font = QFont()
        font.setPointSize(16)
        self.titleLabel.setFont(font)
        self.queryButton = QPushButton(Widget)
        self.queryButton.setObjectName(u"queryButton")
        self.queryButton.setGeometry(QRect(90, 140, 75, 23))
        self.btrLabel = QLabel(Widget)
        self.btrLabel.setObjectName(u"btrLabel")
        self.btrLabel.setGeometry(QRect(365, 90, 71, 20))
        self.viewComboBox = QComboBox(Widget)
        self.viewComboBox.addItem("")
        self.viewComboBox.addItem("")
        self.viewComboBox.addItem("")
        self.viewComboBox.setObjectName(u"viewComboBox")
        self.viewComboBox.setGeometry(QRect(10, 170, 431, 22))
        self.writeButton = QPushButton(Widget)
        self.writeButton.setObjectName(u"writeButton")
        self.writeButton.setGeometry(QRect(10, 140, 75, 23))
        self.ccButton = QPushButton(Widget)
        self.ccButton.setObjectName(u"ccButton")
        self.ccButton.setGeometry(QRect(360, 140, 81, 23))
        self.commandTextEdit = QTextEdit(Widget)
        self.commandTextEdit.setObjectName(u"commandTextEdit")
        self.commandTextEdit.setGeometry(QRect(10, 90, 341, 41))
        self.rsbButton = QPushButton(Widget)
        self.rsbButton.setObjectName(u"rsbButton")
        self.rsbButton.setGeometry(QRect(254, 140, 101, 23))
        self.cqueryButton = QPushButton(Widget)
        self.cqueryButton.setObjectName(u"cqueryButton")
        self.cqueryButton.setGeometry(QRect(170, 400, 111, 23))
        self.ctcButton = QPushButton(Widget)
        self.ctcButton.setObjectName(u"ctcButton")
        self.ctcButton.setGeometry(QRect(550, 140, 111, 23))
        self.btrSpinBox = QSpinBox(Widget)
        self.btrSpinBox.setObjectName(u"btrSpinBox")
        self.btrSpinBox.setGeometry(QRect(360, 110, 81, 22))
        self.btrSpinBox.setMaximum(102400)
        self.btrSpinBox.setValue(10240)
        self.commandComboBox = QComboBox(Widget)
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.addItem("")
        self.commandComboBox.setObjectName(u"commandComboBox")
        self.commandComboBox.setGeometry(QRect(10, 40, 431, 21))
        self.commandComboBox.setEditable(True)
        self.commandComboBox.setMaxVisibleItems(100)
        self.exitButton = QPushButton(Widget)
        self.exitButton.setObjectName(u"exitButton")
        self.exitButton.setGeometry(QRect(680, 400, 75, 23))
        self.wsCheckBox = QCheckBox(Widget)
        self.wsCheckBox.setObjectName(u"wsCheckBox")
        self.wsCheckBox.setGeometry(QRect(310, 400, 81, 17))
        self.flnSpinBox = QSpinBox(Widget)
        self.flnSpinBox.setObjectName(u"flnSpinBox")
        self.flnSpinBox.setGeometry(QRect(95, 400, 61, 22))
        self.flnSpinBox.setMaximum(102400)
        self.flnSpinBox.setValue(5)
        self.flnSpinBox.setDisplayIntegerBase(10)
        self.btrLabel_2 = QLabel(Widget)
        self.btrLabel_2.setObjectName(u"btrLabel_2")
        self.btrLabel_2.setGeometry(QRect(100, 380, 71, 20))
        self.stDoubleSpinBox = QDoubleSpinBox(Widget)
        self.stDoubleSpinBox.setObjectName(u"stDoubleSpinBox")
        self.stDoubleSpinBox.setGeometry(QRect(10, 400, 71, 22))
        self.stDoubleSpinBox.setDecimals(6)
        self.stDoubleSpinBox.setValue(0.500000000000000)
        self.btrLabel_3 = QLabel(Widget)
        self.btrLabel_3.setObjectName(u"btrLabel_3")
        self.btrLabel_3.setGeometry(QRect(10, 380, 71, 20))
        self.stButton = QPushButton(Widget)
        self.stButton.setObjectName(u"stButton")
        self.stButton.setGeometry(QRect(450, 140, 91, 23))

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Form", None))
        self.commandLabel.setText(QCoreApplication.translate("Widget", u"Select or Enter Command", None))
        self.readButton.setText(QCoreApplication.translate("Widget", u"Read", None))
        self.cbButton.setText(QCoreApplication.translate("Widget", u"Clear Buffer", None))
        self.titleLabel.setText(QCoreApplication.translate("Widget", u"Basic I/O", None))
        self.queryButton.setText(QCoreApplication.translate("Widget", u"Query", None))
        self.btrLabel.setText(QCoreApplication.translate("Widget", u"Bytes to Read", None))
        self.viewComboBox.setItemText(0, QCoreApplication.translate("Widget", u"View as ASCII Only", None))
        self.viewComboBox.setItemText(1, QCoreApplication.translate("Widget", u"View mixed ASCII/hexadecimal", None))
        self.viewComboBox.setItemText(2, QCoreApplication.translate("Widget", u"View as hexadecimal only", None))

        self.writeButton.setText(QCoreApplication.translate("Widget", u"Write", None))
        self.ccButton.setText(QCoreApplication.translate("Widget", u"Clear", None))
        self.commandTextEdit.setHtml(QCoreApplication.translate("Widget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*IDN?</p></body></html>", None))
        self.rsbButton.setText(QCoreApplication.translate("Widget", u"Read Status Byte", None))
        self.cqueryButton.setText(QCoreApplication.translate("Widget", u"Continuous Query", None))
        self.ctcButton.setText(QCoreApplication.translate("Widget", u"Copy to Clipboard", None))
        self.commandComboBox.setItemText(0, QCoreApplication.translate("Widget", u"*IDN?", None))
        self.commandComboBox.setItemText(1, QCoreApplication.translate("Widget", u"*CLS", None))
        self.commandComboBox.setItemText(2, QCoreApplication.translate("Widget", u"*RST", None))
        self.commandComboBox.setItemText(3, QCoreApplication.translate("Widget", u"*TST?", None))
        self.commandComboBox.setItemText(4, QCoreApplication.translate("Widget", u"*OPC", None))
        self.commandComboBox.setItemText(5, QCoreApplication.translate("Widget", u"*OPC?", None))
        self.commandComboBox.setItemText(6, QCoreApplication.translate("Widget", u"*WAI", None))
        self.commandComboBox.setItemText(7, QCoreApplication.translate("Widget", u"*ESE", None))
        self.commandComboBox.setItemText(8, QCoreApplication.translate("Widget", u"*ESE?", None))
        self.commandComboBox.setItemText(9, QCoreApplication.translate("Widget", u"*ESR?", None))
        self.commandComboBox.setItemText(10, QCoreApplication.translate("Widget", u"*SRE", None))
        self.commandComboBox.setItemText(11, QCoreApplication.translate("Widget", u"*SRE?", None))
        self.commandComboBox.setItemText(12, QCoreApplication.translate("Widget", u"*STB?", None))
        self.commandComboBox.setItemText(13, QCoreApplication.translate("Widget", u"SYSTem:ERRor:NEXT?", None))
        self.commandComboBox.setItemText(14, QCoreApplication.translate("Widget", u"SYSTem:LOCK:RELease", None))
        self.commandComboBox.setItemText(15, QCoreApplication.translate("Widget", u"MEASure:CONTinuity?", None))
        self.commandComboBox.setItemText(16, QCoreApplication.translate("Widget", u"MEASure:CURRent:AC?", None))
        self.commandComboBox.setItemText(17, QCoreApplication.translate("Widget", u"MEASure:CURRent:DC?", None))
        self.commandComboBox.setItemText(18, QCoreApplication.translate("Widget", u"MEASure:DIODe?", None))
        self.commandComboBox.setItemText(19, QCoreApplication.translate("Widget", u"MEASure:FREQuency?", None))
        self.commandComboBox.setItemText(20, QCoreApplication.translate("Widget", u"MEASure:FRESistance?", None))
        self.commandComboBox.setItemText(21, QCoreApplication.translate("Widget", u"MEASure:PERiod?", None))
        self.commandComboBox.setItemText(22, QCoreApplication.translate("Widget", u"MEASure:RESistance?", None))
        self.commandComboBox.setItemText(23, QCoreApplication.translate("Widget", u"MEASure:TEMPerature?", None))
        self.commandComboBox.setItemText(24, QCoreApplication.translate("Widget", u"MEASure:VOLTage:AC?", None))
        self.commandComboBox.setItemText(25, QCoreApplication.translate("Widget", u"MEASure:VOLTage:DC?", None))
        self.commandComboBox.setItemText(26, QCoreApplication.translate("Widget", u"SYSTem:DATE?", None))
        self.commandComboBox.setItemText(27, QCoreApplication.translate("Widget", u"SYSTem:TIME?", None))

        self.exitButton.setText(QCoreApplication.translate("Widget", u"Exit", None))
        self.wsCheckBox.setText(QCoreApplication.translate("Widget", u"while query", None))
        self.btrLabel_2.setText(QCoreApplication.translate("Widget", u"For Loop #", None))
        self.btrLabel_3.setText(QCoreApplication.translate("Widget", u"Sleep Time", None))
        self.stButton.setText(QCoreApplication.translate("Widget", u"Set Date + Time", None))
    # retranslateUi

